### ISSUE TITLE
缺少了gradle文件夹

### ISSUE THREAD

**Issue by ghost** [Oeeder/mirai-setu-for-bloodyrabbit#1]
缺失gradle文件夹，里面有gradlew的版本信息的，那个不能删掉。

**Comment by Oeeder** [comment]
不好意思，已重新上传文件夹




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Oeeder/mirai-setu-for-bloodyrabbit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月17日(星期二) 晚上9:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Oeeder/mirai-setu-for-bloodyrabbit] 缺少了gradle文件夹 (#1)





 
缺失gradle文件夹，里面有gradlew的版本信息的，那个不能删掉。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
